/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "uber.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ViajeRespuesta *
solicitar_viaje_1(ViajeSolicitud *argp, CLIENT *clnt)
{
	static ViajeRespuesta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, solicitar_viaje,
		(xdrproc_t) xdr_ViajeSolicitud, (caddr_t) argp,
		(xdrproc_t) xdr_ViajeRespuesta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

EstadoRespuesta *
solicitar_estado_1(void *argp, CLIENT *clnt)
{
	static EstadoRespuesta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, solicitar_estado,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_EstadoRespuesta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
terminar_viaje_1(TerminarViajeSolicitud *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, terminar_viaje,
		(xdrproc_t) xdr_TerminarViajeSolicitud, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
