/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_Uber (XDR *xdrs, Uber *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tipo))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->x);
		IXDR_PUT_LONG(buf, objp->y);
		IXDR_PUT_LONG(buf, objp->tipo);
		}
		 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->status))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->tarifa))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->ganancia))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tipo))
				 return FALSE;

		} else {
		objp->x = IXDR_GET_LONG(buf);
		objp->y = IXDR_GET_LONG(buf);
		objp->tipo = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->status))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->tarifa))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->ganancia))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->ganancia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ViajeSolicitud (XDR *xdrs, ViajeSolicitud *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x_origen))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_origen))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ViajeRespuesta (XDR *xdrs, ViajeRespuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_Uber (xdrs, &objp->uber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminarViajeSolicitud (XDR *xdrs, TerminarViajeSolicitud *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x_destino))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_destino))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->costoViaje))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->x_destino);
		IXDR_PUT_LONG(buf, objp->y_destino);
		IXDR_PUT_LONG(buf, objp->costoViaje);
		}
		 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->distancia))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x_destino))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y_destino))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->costoViaje))
				 return FALSE;

		} else {
		objp->x_destino = IXDR_GET_LONG(buf);
		objp->y_destino = IXDR_GET_LONG(buf);
		objp->costoViaje = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->distancia))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->x_destino))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_destino))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costoViaje))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placas, 7,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distancia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_EstadoRespuesta (XDR *xdrs, EstadoRespuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->uber.uber_val, (u_int *) &objp->uber.uber_len, ~0,
		sizeof (Uber), (xdrproc_t) xdr_Uber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadUber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadViajes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->gananciaTotal))
		 return FALSE;
	return TRUE;
}
