/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Uber {
	int x;
	int y;
	int tipo;
	char placas[7];
	int status;
	int tarifa;
	double ganancia;
};
typedef struct Uber Uber;

struct ViajeSolicitud {
	int x_origen;
	int y_origen;
};
typedef struct ViajeSolicitud ViajeSolicitud;

struct ViajeRespuesta {
	Uber uber;
	int costo;
};
typedef struct ViajeRespuesta ViajeRespuesta;

struct TerminarViajeSolicitud {
	int x_destino;
	int y_destino;
	int costoViaje;
	char placas[7];
	double distancia;
};
typedef struct TerminarViajeSolicitud TerminarViajeSolicitud;

struct EstadoRespuesta {
	struct {
		u_int uber_len;
		Uber *uber_val;
	} uber;
	int cantidadUber;
	int cantidadViajes;
	int gananciaTotal;
};
typedef struct EstadoRespuesta EstadoRespuesta;

#define UBER_PRG 0x20000022
#define UBER_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitar_viaje 1
extern  ViajeRespuesta * solicitar_viaje_1(ViajeSolicitud *, CLIENT *);
extern  ViajeRespuesta * solicitar_viaje_1_svc(ViajeSolicitud *, struct svc_req *);
#define solicitar_estado 2
extern  EstadoRespuesta * solicitar_estado_1(void *, CLIENT *);
extern  EstadoRespuesta * solicitar_estado_1_svc(void *, struct svc_req *);
#define terminar_viaje 3
extern  void * terminar_viaje_1(TerminarViajeSolicitud *, CLIENT *);
extern  void * terminar_viaje_1_svc(TerminarViajeSolicitud *, struct svc_req *);
extern int uber_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitar_viaje 1
extern  ViajeRespuesta * solicitar_viaje_1();
extern  ViajeRespuesta * solicitar_viaje_1_svc();
#define solicitar_estado 2
extern  EstadoRespuesta * solicitar_estado_1();
extern  EstadoRespuesta * solicitar_estado_1_svc();
#define terminar_viaje 3
extern  void * terminar_viaje_1();
extern  void * terminar_viaje_1_svc();
extern int uber_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Uber (XDR *, Uber*);
extern  bool_t xdr_ViajeSolicitud (XDR *, ViajeSolicitud*);
extern  bool_t xdr_ViajeRespuesta (XDR *, ViajeRespuesta*);
extern  bool_t xdr_TerminarViajeSolicitud (XDR *, TerminarViajeSolicitud*);
extern  bool_t xdr_EstadoRespuesta (XDR *, EstadoRespuesta*);

#else /* K&R C */
extern bool_t xdr_Uber ();
extern bool_t xdr_ViajeSolicitud ();
extern bool_t xdr_ViajeRespuesta ();
extern bool_t xdr_TerminarViajeSolicitud ();
extern bool_t xdr_EstadoRespuesta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
